### ISSUE TITLE
新版本的企业微信测回是空白

### ISSUE THREAD

**Issue by liupeis** [MustangYM/WeChatICU-ForMac#14]
![image](https://user-images.githubusercontent.com/30236673/85307572-a447d100-b4e2-11ea-9080-ddb600991ca3.png)

**Comment by 8RATH** [comment]
同状况

**Comment by 8RATH** [comment]
似乎这个状况只在安装wechatICU之前已经被撤回的消息上发生

**Comment by youxigit** [comment]
+1

**Comment by MustangYM** [comment]
已经撤回的消息是这样

**Comment by hheng101** [comment]
新版本企业微信，安装wechatICU之后撤回的消息也是这样

**Comment by wusb** [comment]
> 已经撤回的消息是这样

撤回的消息显示为空白是不合理的吧？应该像微信那样转发给自己或者提示撤回消息的内容
